### ISSUE TITLE
duty cycle bug

### ISSUE THREAD

**Issue by farvardin** [utz82/ZX-Spectrum-1-Bit-Routines#1]
here is a basic file where I've tried to modify the duty cycle through the volume channel, it doesn't change the sound.
[squeekerplusbug.tar.gz](https://github.com/utz82/ZX-Spectrum-1-Bit-Routines/files/429415/squeekerplusbug.tar.gz)

**Comment by utz82** [comment]
Thanks for reporting. Should hopefully be fixed now.
